name: Linters

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master


jobs:
    linters:
        name: "Run linters"
        runs-on: ubuntu-latest
        steps:
            - name: Check out code into the Go module directory
              uses: actions/checkout@v2

            - uses: actions/setup-go@v2
              with:
                  go-version: 1.22.0

            - name: Run go vet
              run: "go vet ./..."

            - uses: Install staticcheck
              run: go install honnef.co/go/tools/cmd/staticcheck@latest

            - name: Run staticcheck
              run: "staticcheck ./..."
