name: Linters

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master


jobs:
    linters:
        name: "Run linters"
        runs-on: ubuntu-latest
        steps:
            - name: Check out code into the Go module directory
              uses: actions/checkout@v2

            - uses: actions/setup-go@v2
              with:
<<<<<<< HEAD
                  go-version: 1.22
=======
                  go-version: 1.22.0
>>>>>>> 1b60124 (First workflow)

            - run: "go vet ./..."

            - uses: dominikh/staticcheck-action@v1.3.0
              with:
                  version: "2022.1.3"
                  install-go: false
